<!DOCTYPE html>
<html>
<body>
	<section class="regular slider">
		<div>
			<img src="https://cdn.shopify.com/s/files/1/2631/7576/files/1_banner_color_1800x.jpg?v=1633333499" />
		</div>
		<div>
		<img src="https://cdn.shopify.com/s/files/1/2631/7576/files/3_banner_color_1800x.jpg?v=1633333521" />
		</div>
		<div>
		<img src="https://cdn.shopify.com/s/files/1/2631/7576/files/Banner_5_1800x.jpg?v=1639209020" />
		</div>
		<div>
		<img src="https://cdn.shopify.com/s/files/1/2631/7576/files/1_banner_color_1800x.jpg?v=1633333499" />
		</div>
		<div>
			<img src="https://cdn.shopify.com/s/files/1/2631/7576/files/3_banner_color_1800x.jpg?v=1633333521" />
		</div>
		<div>
			<img src="https://cdn.shopify.com/s/files/1/2631/7576/files/Banner_5_1800x.jpg?v=1639209020" />
		</div>
	</section>
</body>
</html>
